export const DICAS = [
  {cat:'Supermercado',txt:'Compara o preço por quilograma, não o preço total. O produto maior raramente é o mais caro por unidade.',sub:'Poupa até 30% nas compras'},
  {cat:'Supermercado',txt:'Faz uma lista antes de ir ao supermercado e nunca vás com fome. Estudos mostram que compramos 23% mais quando estamos com fome.',sub:'Disciplina = poupança'},
  {cat:'Supermercado',txt:'As marcas brancas da Auchan, Continente e Pingo Doce têm qualidade equivalente às de marca em produtos como massa, arroz e produtos de limpeza.',sub:'Poupa até 40% por produto'},
  {cat:'Supermercado',txt:'Usa a app Too Good To Go para comprar refeições e produtos de padaria com 60-80% de desconto no final do dia.',sub:'Evitas desperdício e poupas'},
  {cat:'Supermercado',txt:'O Lidl e o Aldi têm os preços mais baixos em Portugal para produtos de base. Reserva uma ida por semana para os básicos.',sub:'Menos 15-20% no cabaz'},
  {cat:'Energia',txt:'Muda para o mercado livre de energia. Comercializadores como Galp, EDP Comercial ou Iberdrola têm tarifas até 20% mais baixas do que o mercado regulado.',sub:'Poupa até 200 €/ano'},
  {cat:'Energia',txt:'Liga o esquentador ou termoacumulador em horas de vazio (22h-8h em tarifas bi-horárias). Pode representar uma poupança de 30% na fatura de energia.',sub:'Tarifa bi-horária compensa'},
  {cat:'Energia',txt:'Desliga os aparelhos da ficha em vez de os deixar em standby. Uma TV em standby consome até 15W por hora, o que equivale a cerca de 20€ por ano.',sub:'Pequenos gestos, grande impacto'},
  {cat:'Energia',txt:'Lava a roupa a 30°C em vez de 60°C. Poupa até 60% de energia por ciclo de lavagem, com resultado igual para a maioria das roupas.',sub:'Poupa energia e prolonga a roupa'},
  {cat:'Transportes',txt:'O passe Navegante Metropolitano custa 40€/mês e dá acesso ilimitado a metro, autocarro, comboio e barco em Lisboa. Se usas transportes regularmente, o retorno é imediato.',sub:'Versus combustível: poupança brutal'},
  {cat:'Transportes',txt:'A Via Verde tem promoções frequentes para passes de transportes e combustível. Ativa as notificações da app para não perderes campanhas.',sub:'Descontos sazonais frequentes'},
  {cat:'Transportes',txt:'Verifica se a tua empresa oferece subsídio de transporte ou acordo com operadores de transporte público. É rendimento isento de IRS.',sub:'Benefício fiscal direto'},
  {cat:'Transportes',txt:'Considera a bicicleta para percursos até 5km. Em Lisboa e Porto existem sistemas de bicicletas partilhadas como o GIRA e o Bicimax por menos de 2€/dia.',sub:'Saúde + poupança'},
  {cat:'Finanças',txt:'Activa o arredondamento automático no Revolut ou N26. Cada compra é arredondada para o euro acima e a diferença vai para poupança. Sem esforço.',sub:'Poupança automática invisível'},
  {cat:'Finanças',txt:'Abre uma conta poupança separada e transfere 10% do salário no dia em que o recebes. Tratas o resto como se fosse o teu salário real.',sub:'Regra dos 10% que muda tudo'},
  {cat:'Finanças',txt:'Usa o reembolso do IRS exclusivamente para investir, nunca para consumo. É dinheiro que já não contas — coloca-o a trabalhar por ti.',sub:'Reembolso médio: 500-800€'},
  {cat:'Finanças',txt:'O PPR (Plano Poupança Reforma) dá uma dedução de 20% do valor aplicado no IRS, até 400€/ano. É o retorno imediato mais garantido que existe.',sub:'20% de retorno imediato'},
  {cat:'Finanças',txt:'Consolida os teus cartões de crédito e paga sempre o saldo total no fim do mês. Os juros de crédito em Portugal rondam os 20% ao ano — o pior investimento possível.',sub:'Elimina os juros mais caros'},
  {cat:'Finanças',txt:'Cria um fundo de emergência equivalente a 3-6 meses de despesas antes de investir. Sem ele, qualquer imprevisto desfaz o teu progresso.',sub:'A base de tudo'},
  {cat:'Investimento',txt:'O ETF VWCE (Vanguard FTSE All-World) dá exposição a mais de 3.500 empresas de todo o mundo por um custo anual de apenas 0,22%. É o ponto de partida ideal.',sub:'Diversificação máxima, custo mínimo'},
  {cat:'Investimento',txt:'Investe regularmente (dollar-cost averaging) em vez de esperar pelo momento certo. Quem investe 200€/mês durante 20 anos bate quase sempre quem espera pelo timing perfeito.',sub:'Consistência > perfeição'},
  {cat:'Investimento',txt:'O DeGiro e o Trade Republic são as plataformas com menores comissões em Portugal. O Trade Republic oferece ainda 4% de juro sobre saldo em conta.',sub:'Menos comissões = mais retorno'},
  {cat:'Investimento',txt:'Em Portugal, os juros e mais-valias de investimentos são tributados a 28% (ou englobamento se vantajoso). Considera sempre o impacto fiscal antes de vender.',sub:'IRS sobre investimentos'},
  {cat:'Habitação',txt:'Renegocia a tua hipoteca a cada 2-3 anos. Com a subida das taxas Euribor, muitos bancos estão abertos a renegociar spreads para não perder clientes.',sub:'Potencial de poupança: centenas/mês'},
  {cat:'Habitação',txt:'O crédito ao consumo para obras tem juros altíssimos. Se precisas de renovar casa, pesquisa o Crédito Bonificado à Habitação do IHRU para jovens e famílias.',sub:'Taxas subsidiadas disponíveis'},
  {cat:'Habitação',txt:'Pede uma auditoria energética gratuita à tua câmara municipal. Muitos municípios oferecem este serviço e pode revelar poupanças significativas.',sub:'Serviço gratuito frequentemente'},
  {cat:'Saúde',txt:'Pede sempre a receita verde e compra genéricos na farmácia. Os medicamentos genéricos têm exatamente a mesma substância ativa — a lei obriga a isso.',sub:'Até 80% mais barato'},
  {cat:'Saúde',txt:'O ADSE, se tiveres acesso, pode ser complementado com um seguro de saúde privado de baixo custo para cobrir as lacunas. Compara em comparadores como Raize ou ComparaJá.',sub:'Saúde sem pagar em excesso'},
  {cat:'Saúde',txt:'As consultas nos Centros de Saúde são gratuitas ou têm taxa moderadora baixa. Para patologias não urgentes, evita urgências hospitalares — a taxa é muito superior.',sub:'Sistema público: usa-o com sabedoria'},
  {cat:'Lazer',txt:'O Cartão Jovem (<30 anos) dá descontos de 25-50% em museus, cinemas, transporte e alojamento em Portugal e na Europa. Se ainda és elegível, é obrigatório.',sub:'Descontos em toda a Europa'},
  {cat:'Lazer',txt:'Os museus nacionais em Portugal são gratuitos aos domingos de manhã. Inclui o Museu Nacional de Arte Antiga, o Museu do Azulejo e muitos outros.',sub:'Cultura gratuita ao domingo'},
  {cat:'Lazer',txt:'Partilha subscrições de streaming com família ou amigos. O plano familiar do Spotify custa 17,99€ para 6 pessoas — menos de 3€ por pessoa.',sub:'Partilha = poupança imediata'},
  {cat:'Lazer',txt:'Usa a Biblioteca Municipal. Para além de livros, muitas oferecem acesso gratuito a revistas digitais, filmes e cursos online através de plataformas como a Cantook.',sub:'Acesso a conteúdo gratuito'},
  {cat:'Tecnologia',txt:'Antes de renovar o telemóvel, verifica as ofertas de telemóveis recondicionados certificados. Um iPhone recondicionado pode custar 40% menos com garantia oficial.',sub:'Mesmo produto, menor preço'},
  {cat:'Tecnologia',txt:'Compara tarifas de telemóvel em comparadores como o ComparaJá.pt. Mudar de operador pode poupar 10-20€/mês sem perder qualidade de serviço.',sub:'Poupa até 240€/ano'},
  {cat:'Tecnologia',txt:'Cancela as subscrições que não usas. O português médio tem 4-5 subscrições ativas e usa regularmente apenas 2. Revê os débitos diretos este mês.',sub:'Subscrições esquecidas = dinheiro perdido'},
  {cat:'Alimentação',txt:'Cozinha em grandes quantidades ao fim de semana (meal prep). Além de poupar tempo, reduz o desperdício alimentar e evita a tentação de pedir comida ao domicílio.',sub:'Menos desperdício, mais poupança'},
  {cat:'Alimentação',txt:'A água da torneira em Portugal é segura para beber na maioria dos concelhos. Usar um filtro de carvão ativado elimina qualquer sabor residual por menos de 30€/ano.',sub:'Versus garrafas: poupa centenas/ano'},
  {cat:'Alimentação',txt:'Aproveita as promoções de congelados. Legumes congelados têm o mesmo valor nutricional que frescos e duram meses — sem desperdício.',sub:'Nutrição igual, desperdício zero'},
  {cat:'Finanças',txt:'Separa os teus objetivos financeiros em contas ou subcategorias diferentes. Quem tem objetivos com nomes concretos (Viagem, Emergência, Casa) poupa 2x mais.',sub:'Psicologia do dinheiro em ação'},
  {cat:'Finanças',txt:'Usa a regra 50/30/20: 50% necessidades, 30% desejos, 20% poupança e investimento. É simples, eficaz e adaptável à realidade portuguesa.',sub:'Framework de orçamento comprovada'},
  {cat:'Habitação',txt:'Negocia o arrendamento antes de renovar. Em zonas com alta oferta, pedir uma redução de 5-10% ou incluir despesas (internet, condomínio) é cada vez mais comum.',sub:'Negociar não custa nada'},
  {cat:'Investimento',txt:'Os certificados do Tesouro Aforro e Poupança do Estado Português são garantidos pelo Estado e têm rendimentos competitivos. São ideais para o fundo de emergência.',sub:'Garantia do Estado + rendimento'},
  {cat:'Finanças',txt:'Paga as multas e coimas o mais cedo possível. Em Portugal, podes ter descontos de até 50% se pagares nos primeiros dias. O adiamento tem custo real.',sub:'Desconto por pagamento antecipado'},
  {cat:'Supermercado',txt:'Os cartões de fidelidade do Continente, Pingo Doce e Auchan acumulam descontos reais. Ativa as promoções personalizadas na app antes de cada compra.',sub:'Cartões de fidelidade compensam'},
  {cat:'Finanças',txt:'Faz o exercício do "custo em horas de trabalho". Se ganhas 10€/hora líquidos, um jantar de 40€ custa-te 4 horas de trabalho. Muda a perspetiva sobre o consumo.',sub:'A unidade real do dinheiro'},
  {cat:'Energia',txt:'Instala tomadas inteligentes com timer para o esquentador, aquecedores e outros equipamentos de alto consumo. O investimento recupera-se em 2-3 meses.',sub:'Automação ao serviço da poupança'},
  {cat:'Transportes',txt:'Sempre que possível, combina viagens e recados. Cada saída de carro desnecessária consome combustível, tempo e desgaste. Planear poupa dinheiro.',sub:'A viagem mais cara é a que não se planeia'},
  {cat:'Investimento',txt:'Reinveste sempre os dividendos e juros. O efeito de juros compostos só funciona a 100% quando não retiras os rendimentos. Deixa o dinheiro trabalhar.',sub:'Juros compostos: a oitava maravilha'},
  {cat:'Finanças',txt:'Antes de qualquer compra acima de 50€, espera 48 horas. Este período de reflexão elimina a maioria das compras por impulso sem nenhum sacrifício real.',sub:'A regra das 48 horas'},
  {cat:'Supermercado',txt:'Compra fruta e legumes da época: produtos no pico do amadurecimento custam até 50% menos. Em maio prefere morangos e cerejas, em outubro castanhas e maçãs.',sub:'Sazonalidade poupa muito'},
  {cat:'Supermercado',txt:'Os mercados municipais (Bolhão, Algés, 31 de Janeiro) têm produtos frescos a preço de produtor — entre 20% e 40% mais baratos que o supermercado.',sub:'Compra ao produtor direto'},
  {cat:'Supermercado',txt:'A iniciativa Fruta Feia, em Lisboa, Porto e Coimbra, vende fruta e legumes esteticamente imperfeitos a 30-40% do preço normal. Cabaz semanal.',sub:'Mesma qualidade, sem o preço'},
  {cat:'Supermercado',txt:'Evita produtos pré-cortados, pré-lavados e em saquetas individuais. Pagas até 3x mais pelo mesmo conteúdo. Compra inteiro e prepara em casa.',sub:'Conveniência tem custo escondido'},
  {cat:'Supermercado',txt:'Os granéis (frutos secos, leguminosas, cereais) custam 30-50% menos que os pré-embalados — e geram menos resíduos.',sub:'A granel ganha sempre'},
  {cat:'Supermercado',txt:'Aproveita as promoções "Leva 3, paga 2" só se vais usar tudo. Caso contrário, é desperdício alimentar disfarçado de poupança.',sub:'Promoção real vs ilusão'},
  {cat:'Supermercado',txt:'Faz o pão em casa com máquina automática. Custo por unidade: 0,40€ vs 1,80€ na padaria. Investimento recupera em 6 meses.',sub:'Pão caseiro é 4x mais barato'},
  {cat:'Supermercado',txt:'Os marcadores DDM ("Data de Durabilidade Mínima") e "Validade" são diferentes. DDM é orientativo, "Validade" é obrigatório. Não deites fora à toa.',sub:'Saber ler etiquetas poupa'},
  {cat:'Energia',txt:'Substitui todas as lâmpadas por LED. Consomem 80% menos energia e duram 25 vezes mais. Investimento recupera-se em 6 meses.',sub:'LED: poupa 50€/ano por casa'},
  {cat:'Energia',txt:'Coloca papel alumínio atrás dos radiadores em paredes exteriores. Reflete o calor para dentro de casa e aumenta eficiência em 5-10%.',sub:'Truque de 1€ que poupa muito'},
  {cat:'Energia',txt:'Programa o termostato para 19-20°C no inverno. Cada grau a mais aumenta o consumo em 7%. Camada extra de roupa é mais barata que aquecimento.',sub:'19°C é o ideal saúde-poupança'},
  {cat:'Energia',txt:'Limpa os filtros do ar condicionado mensalmente. Equipamento sujo gasta 15-20% mais e a qualidade do ar piora.',sub:'Manutenção paga-se sozinha'},
  {cat:'Energia',txt:'Compra eletrodomésticos com classe A+++ (frigoríficos, máquinas). O custo extra paga-se em 3-4 anos com a poupança em energia.',sub:'Custo total de propriedade'},
  {cat:'Energia',txt:'Toma duches de 5 minutos em vez de 10. Poupa 30 litros de água quente por dia, equivalente a 90€/ano em energia + água.',sub:'5 min vs 10 min: 90€/ano'},
  {cat:'Energia',txt:'Instala redutores de caudal nas torneiras (€5 cada). Reduzem consumo de água em 40% sem afetar a pressão percebida.',sub:'15€ poupam 100€/ano'},
  {cat:'Energia',txt:'Descongela frigorífico e congelador a cada 6 meses. O gelo acumulado faz o equipamento gastar até 30% mais energia.',sub:'15 min de manutenção, 50€/ano'},
  {cat:'Energia',txt:'Verifica o isolamento das janelas com uma folha de papel. Se cair quando fechas a janela, está mal isolada — investe em borrachas ou vedantes.',sub:'Isolamento = -25% em aquecimento'},
  {cat:'Energia',txt:'Aproveita as horas de sol para secar a roupa em vez de usar a máquina de secar. Cada ciclo gasta 2-3 kWh — cerca de 50 cêntimos.',sub:'Sol é a forma mais barata'},
  {cat:'Energia',txt:'O auto-consumo solar tem subsídio do PRR para particulares. Investe 4-6 mil euros e recupera em 7-9 anos com 25 anos de garantia.',sub:'Solar com subsídio público'},
  {cat:'Transportes',txt:'Verifica a pressão dos pneus mensalmente. Pneus mal calibrados aumentam o consumo de combustível em 8% e desgastam-se mais rápido.',sub:'5 min/mês, 8% menos combustível'},
  {cat:'Transportes',txt:'A app GasNow mostra os postos de combustível mais baratos num raio de 10km. Diferenças de 8 a 12 cêntimos/L são comuns na mesma cidade.',sub:'Mesma cidade, preços diferentes'},
  {cat:'Transportes',txt:'Os Postos Galp e Repsol dão 10 cêntimos/L de desconto com cartão Continente ou Pingo Doce. Acumula em viagens longas.',sub:'10c/L = 5€ por depósito'},
  {cat:'Transportes',txt:'Conduz em modo eco: acelerações suaves, travagens antecipadas, manter velocidade constante. Reduz consumo em 10-15%.',sub:'Estilo de condução importa'},
  {cat:'Transportes',txt:'O BlaBlaCar é 50-70% mais barato que o comboio em rotas longas (Lisboa-Porto: ~12€ vs 25€) e ainda permite conhecer pessoas.',sub:'Boleia partilhada é económica'},
  {cat:'Transportes',txt:'Combina recados numa só saída. Cada arranque a frio do motor consome 3-4x mais combustível que a condução normal.',sub:'Planeamento poupa combustível'},
  {cat:'Transportes',txt:'Considera os carros eléctricos partilhados (Free2move, Bolt Drive) em vez de táxi/Uber para distâncias 5-15km. Tarifa por minuto compensa.',sub:'Eléctricos partilhados ganham'},
  {cat:'Transportes',txt:'O Estacionamento EMEL/EPP tem desconto residente. Regista-te no portal — passas a pagar 30€/mês em vez de €1,80/hora.',sub:'Residente paga 90% menos'},
  {cat:'Finanças',txt:'O cartão Activobank Rendimento dá 1% de cashback em todas as compras sem mensalidade. Para gastos de 1.000€/mês = 120€/ano de volta.',sub:'Cashback automático'},
  {cat:'Finanças',txt:'O Revolut Standard é gratuito com câmbio sem comissão até 1.000€/mês. Ideal para viagens e compras online em moeda estrangeira.',sub:'Câmbio sem comissão'},
  {cat:'Finanças',txt:'Negoceia a anuidade dos cartões de crédito. Muitos bancos isentam clientes que ameaçam mudar — pede o gestor de conta.',sub:'Negociar não custa nada'},
  {cat:'Finanças',txt:'Cancela cartões de crédito que não usas. Mantêm anuidade (15-30€/ano cada) mesmo sem movimentos. Liga ao banco e pede cancelamento.',sub:'Cartões adormecidos custam'},
  {cat:'Finanças',txt:'Verifica os extratos do cartão de crédito mensalmente. Cobranças duplicadas, ajustes cambiais errados e fraudes pequenas passam despercebidas.',sub:'5 min/mês evita fraudes'},
  {cat:'Finanças',txt:'Activa SMS ou notificação push para todos os movimentos do cartão. Detetas fraudes em tempo real e reclamas dentro do prazo (60 dias).',sub:'Notificações = segurança'},
  {cat:'Finanças',txt:'Cria uma conta separada apenas para débitos diretos (renda, água, luz, internet). Tens controlo total e o salário fica protegido.',sub:'Separação = controlo'},
  {cat:'Finanças',txt:'Pede sempre fatura com NIF — mesmo em cafés e padarias. Cada euro contribui para deduções no IRS no fim do ano.',sub:'Faturas = dedução IRS'},
  {cat:'Finanças',txt:'A app Splitwise (gratuita) gere despesas partilhadas com casa, amigos ou casais. Acaba com discussões sobre quem pagou o quê.',sub:'Sem mais discussões de €€'},
  {cat:'Finanças',txt:'Usa apenas multibanco da tua rede bancária. Outros bancos cobram 2-3€ por levantamento — em 12 meses, são 30-40€ desnecessários.',sub:'MB próprio é gratuito'},
  {cat:'Finanças',txt:'Marca um dia fixo por semana (15 min) para revisão das tuas finanças. Hábito automatizado vence força de vontade.',sub:'Hábito > motivação'},
  {cat:'Finanças',txt:'Os MB Way têm limite mensal — verifica no Portal do Cliente do teu banco e ajusta antes de pagamentos importantes.',sub:'Evita pagamentos rejeitados'},
  {cat:'Finanças',txt:'Para emprestar dinheiro a amigos ou família, usa apps como Splitwise IOU. Documentado, sem juros, evita problemas.',sub:'Empréstimos sem stress'},
  {cat:'Finanças',txt:'O DNS bancário (transferência interna PT) é instantâneo e gratuito até €500. Usa-o em vez de PayPal ou Western Union entre amigos.',sub:'Transferências grátis em PT'},
  {cat:'Finanças',txt:'Os "regalos" dos cartões premium (lounges, milhas, cashback) só compensam se gastas o suficiente. Calcula o break-even antes de pagar anuidade.',sub:'Premium nem sempre compensa'},
  {cat:'Finanças',txt:'O Portal das Finanças tem simulador de IRS — projeta o teu reembolso antes de Junho. Permite preparação financeira atempada.',sub:'Sabe o IRS antes do prazo'},
  {cat:'Finanças',txt:'Em casa partilhada, define quem paga o quê em escrito (até num WhatsApp). Acordos verbais geram conflitos que podem custar a amizade.',sub:'Documentar protege relações'},
  {cat:'Finanças',txt:'Os cartões pré-pagos (Bankinter Coin, MB Net) protegem-te em compras online de risco. O limite é o saldo carregado.',sub:'Compras online seguras'},
  {cat:'Finanças',txt:'Verifica o teu Mapa de Responsabilidades de Crédito no Banco de Portugal (gratuito, online). Mostra todos os créditos ativos e atrasos.',sub:'Conhece o teu perfil de crédito'},
  {cat:'Finanças',txt:'A regra do "não me lembro": se não te lembras de uma despesa fixa há mais de 6 meses, cancela. Provavelmente não a precisas.',sub:'Memória vs débito direto'},
  {cat:'Finanças',txt:'Instala apps tipo Splitwise para casais — define orçamento conjunto, despesas partilhadas, e elimina conflitos sobre dinheiro em casa.',sub:'Casais sem brigas de €'},
  {cat:'Investimento',txt:'Lê "The Simple Path to Wealth" do JL Collins ou o Bogleheads Guide. Bases para investidor passivo de longo prazo, sem complicações.',sub:'2 livros = 90% do conhecimento'},
  {cat:'Investimento',txt:'O JustETF.com é a melhor ferramenta para comparar ETFs disponíveis na Europa. Filtra por TER, performance e domicílio fiscal.',sub:'Ferramenta indispensável'},
  {cat:'Investimento',txt:'Diversifica geograficamente: 60-70% mundo desenvolvido, 20-25% Europa, 5-15% mercados emergentes. Reduz risco sem sacrificar retorno.',sub:'Geografia importa'},
  {cat:'Investimento',txt:'Não invistas dinheiro de que vais precisar nos próximos 5 anos. O mercado pode cair 30-40% em qualquer ano — não venderias forçado.',sub:'Horizonte temporal manda'},
  {cat:'Investimento',txt:'Os fundos com TER (Total Expense Ratio) acima de 1% comem o teu retorno a longo prazo. Preferes ETFs com TER inferior a 0,30%.',sub:'TER baixo = mais retorno'},
  {cat:'Investimento',txt:'As crypto não devem ser mais de 5-10% do teu portfolio total. Volatilidade extrema, regulação ainda incerta. Especulação, não investimento.',sub:'Crypto: alocação pequena'},
  {cat:'Investimento',txt:'Verifica o teu portfolio trimestralmente, não diariamente. Ver flutuações diárias gera ansiedade e leva a decisões emocionais erradas.',sub:'Menos é mais (em verificações)'},
  {cat:'Investimento',txt:'O DeGiro tem custódia gratuita até 2.500€/mês na "ETF Core Selection" — lista de ETFs sem comissão de compra. Vê antes de investir.',sub:'Comissões zero possível'},
  {cat:'Investimento',txt:'Quem vendeu em pânico em Março 2020 perdeu o melhor recovery da história. Quem ficou ganhou 70% nos 18 meses seguintes.',sub:'Ficar parado vence o pânico'},
  {cat:'Investimento',txt:'As Letras do Tesouro a 1 ano em Portugal são alternativa segura aos depósitos a prazo, com yield similar e garantia do Estado.',sub:'Garantia do Estado'},
  {cat:'Investimento',txt:'Os REITs (Real Estate Investment Trusts) dão exposição imobiliária sem comprar casa. Yield típico 3-6% mais valorização.',sub:'Imobiliário sem comprar casa'},
  {cat:'Investimento',txt:'Considera obrigações ligadas à inflação (TIPS, OEIC inflation-linked) para preservar poder de compra em períodos inflacionistas.',sub:'Proteção contra inflação'},
  {cat:'Investimento',txt:'O custo de oportunidade do dinheiro parado é a inflação. Não fiques só em conta poupança a 0% — perdes 3% ao ano em poder de compra.',sub:'Dinheiro parado perde valor'},
  {cat:'Investimento',txt:'Em Portugal, mais-valias detidas mais de 12 meses podem ser englobadas (taxas progressivas em vez de 28% fixos). Vale a pena para rendimentos baixos.',sub:'Englobamento pode compensar'},
  {cat:'Investimento',txt:'Reinveste 100% dos dividendos durante a fase de acumulação (antes dos 50). O efeito de juros compostos só funciona a 100% sem retiradas.',sub:'Acumulação total < 50 anos'},
  {cat:'Investimento',txt:'Não tentes acertar o timing do mercado. Quem investe 200€/mês durante 20 anos bate 95% dos investidores que tentam timing perfeito.',sub:'Consistência ganha'},
  {cat:'Investimento',txt:'O Trade Republic dá 4% sobre saldo em conta (até 50k€) e zero comissões em ETFs. Útil para liquidez de curto prazo.',sub:'Cash com juro decente'},
  {cat:'Investimento',txt:'Não invistas em algo que não consegues explicar a um amigo em 1 minuto. Se não percebes, é especulação, não investimento.',sub:'Regra do 1 minuto'},
  {cat:'Investimento',txt:'O índice S&P 500 deu retorno médio anual de ~10% nos últimos 100 anos. Replicar isso é o suficiente para te tornar rico — não precisas de bater o índice.',sub:'Igualar S&P 500 chega'},
  {cat:'Investimento',txt:'Os Certificados de Reforma do Estado (PPR público) têm taxas baixíssimas e garantia. Alternativa segura aos PPRs bancários comerciais.',sub:'PPR público existe'},
  {cat:'Habitação',txt:'O IMI tem isenção temporária para 1ª habitação até 125.000€ de Valor Patrimonial Tributário. Pede no Portal das Finanças após a compra.',sub:'Isenção pede-se, não vem'},
  {cat:'Habitação',txt:'O Cartão Família Numerosa (4+ filhos) dá 50% de desconto em IMI. Verifica se és elegível na Câmara Municipal.',sub:'Família numerosa = -50% IMI'},
  {cat:'Habitação',txt:'Compara seguros de habitação anualmente. Os bancos forçam um seguro com o crédito, mas tens 30 dias para cancelar e contratar outro mais barato.',sub:'Seguro do banco raramente é o melhor'},
  {cat:'Habitação',txt:'O TAEG é mais importante que a TAN no crédito habitação. Inclui todos os custos (comissões, seguros, impostos) — é o número real.',sub:'TAEG é o que importa'},
  {cat:'Habitação',txt:'Pede tarifa social da água ao teu município. Disponível para baixos rendimentos — desconto até 50% na fatura.',sub:'Tarifa social existe'},
  {cat:'Habitação',txt:'Obras de reabilitação têm IVA reduzido a 6% (em vez de 23%) com declaração da Câmara. Pede antes da factura.',sub:'IVA 6% para reabilitação'},
  {cat:'Habitação',txt:'Considera arrendar quartos extras (estudantil ou alojamento local). Em Lisboa/Porto, um quarto rende 400-600€/mês.',sub:'Quartos extras geram renda'},
  {cat:'Habitação',txt:'Ao comprar casa, soma 8-10% extra ao preço para custos (IMT, IS, escritura, registo, comissões). Não te deixes apanhar de surpresa.',sub:'10% extra além do preço'},
  {cat:'Habitação',txt:'O crédito jovem (<35 anos) tem condições preferenciais em Crédito Agrícola, CGD e Montepio. Spreads e prazos melhores.',sub:'Jovens têm vantagem'},
  {cat:'Habitação',txt:'Pede para retirar a comissão de manutenção do crédito habitação. Muitos bancos isentam para evitar perder o cliente.',sub:'Pedir custa zero'},
  {cat:'Habitação',txt:'Verifica o certificado energético antes de comprar. Casa A/B custa 50% menos em aquecimento que F/G — diferença de 1.000€/ano.',sub:'Certificado A/B compensa'},
  {cat:'Habitação',txt:'O Programa Mais Habitação dá subsídio de renda em zonas pressionadas (Lisboa, Porto, Algarve). Verifica elegibilidade.',sub:'Subsídio de renda existe'},
  {cat:'Habitação',txt:'Os terrenos rústicos têm IMI muito baixo. Para casas modulares ou prefab, é uma alternativa 40-60% mais barata que urbanos.',sub:'Rústicos são alternativa'},
  {cat:'Saúde',txt:'Os exames preventivos anuais (rastreio cancro, análises) são gratuitos no SNS. Pede ao médico de família — usa o que já pagaste em impostos.',sub:'SNS preventivo é grátis'},
  {cat:'Saúde',txt:'Compra óculos online em sites como Polette, Mister Spex ou Lentiamo. Mesma graduação, preços 40-60% inferiores aos óculos físicos.',sub:'Óculos online: -50%'},
  {cat:'Saúde',txt:'Os Centros de Saúde têm consulta de medicina dentária pública. Limpezas e tratamentos básicos a preços simbólicos vs privado.',sub:'Dentista público existe'},
  {cat:'Saúde',txt:'Liga primeiro à Saúde 24 (808 24 24 24) antes de ires à urgência. Gratuito, 24/7, evita taxas moderadoras desnecessárias.',sub:'Saúde 24 antes da urgência'},
  {cat:'Saúde',txt:'A ADSE/ADM comparticipa consultas de psicologia até 70%. Verifica antes de pagar inteiro num privado.',sub:'Psicologia comparticipada'},
  {cat:'Saúde',txt:'Os pavilhões municipais têm aulas de ginástica, natação e desporto a preços simbólicos. Alternativa aos ginásios privados de 35€/mês.',sub:'Desporto público acessível'},
  {cat:'Saúde',txt:'Os medicamentos de marca e genéricos têm exatamente a mesma substância ativa — exigência da AIM. Diferença de preço: 30-80%.',sub:'Genérico = mesmo medicamento'},
  {cat:'Saúde',txt:'Compra suplementos online em sites como Iherb ou MyProtein. Os mesmos produtos custam 40-60% mais nas farmácias e parafarmácias.',sub:'Suplementos online: -50%'},
  {cat:'Lazer',txt:'O cinema ao domingo de manhã é mais barato na maioria das salas (Cinemas NOS, UCI). Mesmo filme, mesma experiência, 40% do preço.',sub:'Cinema domingo manhã'},
  {cat:'Lazer',txt:'A app PressReader, gratuita via Biblioteca Municipal, dá acesso a 7.000+ jornais e revistas internacionais. Sem subscrição extra.',sub:'7000 publicações grátis'},
  {cat:'Lazer',txt:'Os festivais grandes (NOS Alive, Sumol Summer) têm ofertas paralelas gratuitas — fringes, festas afilhadas, eventos secundários.',sub:'Festivais têm fringes grátis'},
  {cat:'Lazer',txt:'Reserva férias últimos 30 dias antes da partida em comparadores como Skyscanner ou Edreams. Os preços costumam cair na véspera.',sub:'Last minute compensa'},
  {cat:'Lazer',txt:'Faz piqueniques nos parques da cidade (Eduardo VII, Monsanto, Cidade) em vez de comeres em restaurantes. Atmosfera bonita, custo zero.',sub:'Piquenique > restaurante'},
  {cat:'Lazer',txt:'As caminhadas guiadas em Parques Naturais (PNPG, PN Sintra-Cascais) são gratuitas com guias certificados. Inscrição online.',sub:'Natureza com guia: grátis'},
  {cat:'Lazer',txt:'O bilhete combinado dos museus de Lisboa custa 9€ e dá acesso a 7 museus em 24h. Vale o dia inteiro de cultura.',sub:'7 museus por 9€'},
  {cat:'Tecnologia',txt:'Compra acessórios genéricos (Anker, Aukey, Baseus) em vez dos da Apple/Samsung. Qualidade equivalente, preço 60-80% inferior.',sub:'Genéricos qualidade-preço'},
  {cat:'Tecnologia',txt:'Considera laptops recondicionados em sites como Refurbed.pt ou BackMarket. Garantia, mesma qualidade, 30-40% mais baratos.',sub:'Recondicionados garantidos'},
  {cat:'Tecnologia',txt:'Vende equipamentos antigos no OLX ou Vinted antes que percam valor. Um iPhone com 2 anos vale ainda 40-50% do preço novo.',sub:'Aproveita valor residual'},
  {cat:'Tecnologia',txt:'Limita os equipamentos sempre ligados. TV em standby, consola, router consomem 24/7 — em conjunto pode dar 100€/ano.',sub:'Standby acumula'},
  {cat:'Tecnologia',txt:'Os Repair Cafés em Lisboa e Porto reparam equipamentos gratuitamente uma vez por mês. Voluntários consertam o que normalmente deitas fora.',sub:'Reparação gratuita existe'},
  {cat:'Tecnologia',txt:'Combina iCloud (5GB), Google Drive (15GB) e OneDrive (5GB) gratuitos. Tens 25GB de backup grátis sem pagar serviços premium.',sub:'25GB grátis combinados'},
  {cat:'Tecnologia',txt:'Antes de comprar uma smart TV, calcula o custo total: TV + Netflix + Spotify + outras subs. Por vezes uma TV "burra" + Chromecast sai mais barato.',sub:'Smart TV tem custo escondido'},
  {cat:'Alimentação',txt:'Café tomado em casa: 0,15€/copo. Café em pastelaria: 1€. Diferença anual (1 café/dia): 310€ — para uma reforma decente.',sub:'Café diário = 310€/ano'},
  {cat:'Alimentação',txt:'Reduz consumo de carne para 1-2x por semana. Proteínas vegetais (lentilhas, grão, feijão) custam 1/4 e são igualmente nutritivas.',sub:'Carne menos = poupar mais'},
  {cat:'Alimentação',txt:'Marmita do almoço poupa 1.500-2.500€/ano vs comer fora 5x/semana. 30 min de prep no domingo paga uma viagem.',sub:'Marmita = 1 férias/ano'},
  {cat:'Alimentação',txt:'Os ovos são a proteína mais barata e nutritiva. Base de muitas refeições rápidas: omeletes, escalfados, mexidos — sem sair caro.',sub:'Ovos: proteína #1'},
  {cat:'Alimentação',txt:'Compra ervas aromáticas em vaso (3€) em vez de embalagens (2€/uso). Duram meses, sempre frescas, sem desperdício.',sub:'Vaso > embalagem'},
  {cat:'Alimentação',txt:'Aproveita restos do jantar para o almoço do dia seguinte. Cozinha sempre 50% mais — automatiza marmitas sem esforço extra.',sub:'Cozinhar 1x = comer 2x'},
  {cat:'Alimentação',txt:'Os "almoços executivos" dos restaurantes (8-12€) incluem entrada + prato + sobremesa + café. À noite custaria 25€.',sub:'Almoços executivos compensam'},
  {cat:'Alimentação',txt:'Faz o teu próprio iogurte com iogurteira eléctrica (€20). Custo por unidade: 0,15€ vs 0,80€ no supermercado. ROI em 2 meses.',sub:'Iogurte caseiro: 1/5 do preço'},
  {cat:'Trabalho',txt:'Negoceia o salário a cada 18-24 meses. Não esperes que sejam eles a propor — quem pede, recebe. Quem não pede, fica para trás.',sub:'Pedir é parte do trabalho'},
  {cat:'Trabalho',txt:'Documenta os teus resultados mensalmente num ficheiro. Quando pedires aumento, tens dados concretos em vez de "acho que mereço".',sub:'Dados batem opinião'},
  {cat:'Trabalho',txt:'O teletrabalho poupa €2.000-4.000/ano em transporte, almoços e roupa de trabalho. Negoceia 2-3 dias/semana.',sub:'Teletrabalho = -3k€/ano'},
  {cat:'Trabalho',txt:'Os benefícios em espécie (saúde, formação, transportes) são isentos de IRS até certos limites. Pede em vez de aumento bruto.',sub:'Benefícios > aumento bruto'},
  {cat:'Trabalho',txt:'O subsídio de alimentação até 10€/dia (cartão refeição) é isento de IRS e Segurança Social. Vantajoso vs aumento equivalente.',sub:'Cartão refeição é vantajoso'},
  {cat:'Trabalho',txt:'Considera trabalho freelance complementar em plataformas como Upwork, Fiverr ou Workana. €100-500/mês extras pagam férias.',sub:'Freelance complementa'},
  {cat:'Trabalho',txt:'Investe em formação certificada da tua área. Ascendes 30% mais rápido em salário do que sem formação.',sub:'Formação acelera carreira'},
  {cat:'Trabalho',txt:'70% das vagas seniores nunca são publicadas. Mantém o LinkedIn ativo, conecta-te com recruiters da tua área.',sub:'LinkedIn ativo abre portas'},
  {cat:'Trabalho',txt:'Pede mentoria a profissionais 5-10 anos à frente. Investimento de 0€, ROI altíssimo. A maioria aceita se pedires bem.',sub:'Mentoria: ROI infinito'},
  {cat:'Trabalho',txt:'As linhas verdes para empreendedores (BPI Empreender, IAPMEI) financiam ideias com baixo risco. Consulta antes de aceitar emprego.',sub:'Empreender é opção'},
  {cat:'Trabalho',txt:'Os bónus por objetivos têm tributação favorável até 5x o salário base. Negoceia componente variável vs aumento fixo se possível.',sub:'Bónus tributados melhor'},
  {cat:'Impostos',txt:'As deduções IRS por casa, saúde e educação dão até 1.000€/ano de retorno. Guarda todas as faturas com NIF ao longo do ano.',sub:'NIF = dedução IRS'},
  {cat:'Impostos',txt:'O Programa SIMPLEX permite IRS automático para muitos contribuintes. Verifica os dados antes de aceitar — pode ter erros a teu favor ou contra.',sub:'IRS automático: verifica'},
  {cat:'Impostos',txt:'Casados podem optar por declaração separada de IRS. Em alguns casos compensa fiscalmente — simula ambos os cenários.',sub:'Separado pode compensar'},
  {cat:'Impostos',txt:'As doações a IPSS dão dedução IRS de 25%. Compensa fiscalmente e socialmente — escolhe causas em que acreditas.',sub:'Solidariedade dedutível'},
  {cat:'Impostos',txt:'Paga sempre o IUC antes da data limite (Maio). Após o prazo, há agravamento mensal — pequena distração custa 50-100€.',sub:'IUC sem agravamento'},
  {cat:'Impostos',txt:'As mais-valias até 3.470€/ano em IRS estão isentas. Aproveita o threshold anual fazendo realizações tácticas.',sub:'Threshold anual existe'},
  {cat:'Impostos',txt:'As despesas de saúde com IVA são dedutíveis no IRS até 2,5% do rendimento. Pede sempre fatura nas farmácias e médicos.',sub:'Saúde dedutível 2,5%'},
  {cat:'Impostos',txt:'Os tributos autárquicos (taxas, derramas) variam entre municípios. Antes de mudar de cidade, consulta as taxas locais.',sub:'Município importa fiscalmente'},
  {cat:'Seguros',txt:'Compara seguro automóvel anualmente em portais como ComparaJá ou Lifesy. A diferença entre seguradoras pode ser de 200-400€/ano.',sub:'Comparar = poupar 300€'},
  {cat:'Seguros',txt:'Aumenta a franquia do seguro auto. Pagas premium mais baixo, e só usas para sinistros graves — onde a franquia é insignificante.',sub:'Franquia alta, premium baixo'},
  {cat:'Seguros',txt:'O seguro de saúde com tabela de comparticipação (50-70% do médico) é mais barato que sem. Para usuários esporádicos compensa.',sub:'Comparticipação reduz preço'},
  {cat:'Seguros',txt:'As coberturas básicas (RC, danos próprios) bastam para a maioria. Extras (assistência viagem, vidros) podem já estar nos cartões.',sub:'Não duplicar coberturas'},
  {cat:'Seguros',txt:'Os seguros multirriscos cobrem casa + recheio. Verifica o limite de capital seguro — se for baixo, em sinistro grande não recebes o suficiente.',sub:'Capital seguro suficiente'},
  {cat:'Seguros',txt:'O auto-renewal é o calcanhar de Aquiles dos seguros. Anota o vencimento no calendário e renegoceia ou muda 30 dias antes.',sub:'Renovação = oportunidade'},
  {cat:'Filhos',txt:'O Abono de Família é cumulativo com Bolsa de Estudo. Pede ambos na Segurança Social e na escola — não são incompatíveis.',sub:'Abono + Bolsa cumuláveis'},
  {cat:'Filhos',txt:'Os jardins de infância públicos e IPSS custam 15-30% dos privados. Lista de espera grande mas vale a pena inscrever desde o nascimento.',sub:'Públicos têm fila — inscreve cedo'},
  {cat:'Filhos',txt:'Os manuais escolares são reembolsados pela Escola Virtual ou pelo mealheiro municipal. Confirma com o agrupamento.',sub:'Manuais grátis pedidos'},
  {cat:'Filhos',txt:'As atividades extra-curriculares municipais (música, desporto, línguas) custam 5-15€/mês — alternativa a privados de 50-80€.',sub:'Município ensina barato'},
  {cat:'Filhos',txt:'Considera o seguro escolar do agrupamento (cobertura básica) por <5€/ano em vez de seguros privados redundantes.',sub:'Seguro escolar é suficiente'},
  {cat:'Reforma',txt:'Calcula o teu valor de reforma estimado em www.seg-social.pt. Sem este número, qualquer planeamento é cego.',sub:'Sabe o teu valor'},
  {cat:'Reforma',txt:'O PPR é mais flexível do que pensas. Podes resgatar com penalidade fiscal mas sem perder valor — útil em emergências.',sub:'PPR não tranca o dinheiro'},
  {cat:'Reforma',txt:'O Complemento Solidário para Idosos (CSI) é para pensões abaixo de €493/mês. Verifica elegibilidade na Segurança Social.',sub:'CSI completa pensões baixas'},
  {cat:'Reforma',txt:'Investe 10-15% do rendimento desde os 25 anos. Atinges reforma confortável aos 60 — dependendo do estilo de vida.',sub:'10-15% desde cedo'},
  {cat:'Reforma',txt:'Reformar aos 60 vs 65 reduz pensão em 30%. Calcula o trade-off antes de decidir — qualidade de vida vs valor recebido.',sub:'5 anos a menos = -30%'},
  {cat:'Mindset',txt:'Define os teus "valores financeiros". Onde gastas sem culpa? Onde cortas sem dor? Personaliza o teu orçamento à tua vida real.',sub:'Valores definem orçamento'},
  {cat:'Mindset',txt:'Compara-te com quem ganhava como tu há 10 anos, não com quem ganha 3x mais. Perspetiva temporal acaba com inveja paralisante.',sub:'Compara para trás, não para o lado'},
  {cat:'Mindset',txt:'Os ricos discretos têm mais riqueza que os ricos visíveis. Estilo de vida modesto + investimento consistente vence ostentação.',sub:'Discrição constrói riqueza'},
  {cat:'Mindset',txt:'Não confundas custo com valor. Algo barato que dura 10 anos vence algo caro que dura 1. Custo total importa, preço inicial não.',sub:'Custo total > preço inicial'},
];

export function getDicaDoDia() {
  const hoje = new Date();
  const diaDoAno = Math.floor((hoje - new Date(hoje.getFullYear(), 0, 0)) / (1000 * 60 * 60 * 24));
  const idx = diaDoAno % DICAS.length;
  return DICAS[idx];
}
