export const DICAS = [
  {cat:'Supermercado',txt:'Compara o preço por quilograma, não o preço total. O produto maior raramente é o mais caro por unidade.',sub:'Poupa até 30% nas compras'},
  {cat:'Supermercado',txt:'Faz uma lista antes de ir ao supermercado e nunca vás com fome. Estudos mostram que compramos 23% mais quando estamos com fome.',sub:'Disciplina = poupança'},
  {cat:'Supermercado',txt:'As marcas brancas da Auchan, Continente e Pingo Doce têm qualidade equivalente às de marca em produtos como massa, arroz e produtos de limpeza.',sub:'Poupa até 40% por produto'},
  {cat:'Supermercado',txt:'Usa a app Too Good To Go para comprar refeições e produtos de padaria com 60-80% de desconto no final do dia.',sub:'Evitas desperdício e poupas'},
  {cat:'Supermercado',txt:'O Lidl e o Aldi têm os preços mais baixos em Portugal para produtos de base. Reserva uma ida por semana para os básicos.',sub:'Menos 15-20% no cabaz'},
  {cat:'Energia',txt:'Muda para o mercado livre de energia. Comercializadores como Galp, EDP Comercial ou Iberdrola têm tarifas até 20% mais baixas do que o mercado regulado.',sub:'Poupa até 200 €/ano'},
  {cat:'Energia',txt:'Liga o esquentador ou termoacumulador em horas de vazio (22h-8h em tarifas bi-horárias). Pode representar uma poupança de 30% na fatura de energia.',sub:'Tarifa bi-horária compensa'},
  {cat:'Energia',txt:'Desliga os aparelhos da ficha em vez de os deixar em standby. Uma TV em standby consome até 15W por hora, o que equivale a cerca de 20€ por ano.',sub:'Pequenos gestos, grande impacto'},
  {cat:'Energia',txt:'Lava a roupa a 30°C em vez de 60°C. Poupa até 60% de energia por ciclo de lavagem, com resultado igual para a maioria das roupas.',sub:'Poupa energia e prolonga a roupa'},
  {cat:'Transportes',txt:'O passe Navegante Metropolitano custa 40€/mês e dá acesso ilimitado a metro, autocarro, comboio e barco em Lisboa. Se usas transportes regularmente, o retorno é imediato.',sub:'Versus combustível: poupança brutal'},
  {cat:'Transportes',txt:'A Via Verde tem promoções frequentes para passes de transportes e combustível. Ativa as notificações da app para não perderes campanhas.',sub:'Descontos sazonais frequentes'},
  {cat:'Transportes',txt:'Verifica se a tua empresa oferece subsídio de transporte ou acordo com operadores de transporte público. É rendimento isento de IRS.',sub:'Benefício fiscal direto'},
  {cat:'Transportes',txt:'Considera a bicicleta para percursos até 5km. Em Lisboa e Porto existem sistemas de bicicletas partilhadas como o GIRA e o Bicimax por menos de 2€/dia.',sub:'Saúde + poupança'},
  {cat:'Finanças',txt:'Activa o arredondamento automático no Revolut ou N26. Cada compra é arredondada para o euro acima e a diferença vai para poupança. Sem esforço.',sub:'Poupança automática invisível'},
  {cat:'Finanças',txt:'Abre uma conta poupança separada e transfere 10% do salário no dia em que o recebes. Tratas o resto como se fosse o teu salário real.',sub:'Regra dos 10% que muda tudo'},
  {cat:'Finanças',txt:'Usa o reembolso do IRS exclusivamente para investir, nunca para consumo. É dinheiro que já não contas — coloca-o a trabalhar por ti.',sub:'Reembolso médio: 500-800€'},
  {cat:'Finanças',txt:'O PPR (Plano Poupança Reforma) dá uma dedução de 20% do valor aplicado no IRS, até 400€/ano. É o retorno imediato mais garantido que existe.',sub:'20% de retorno imediato'},
  {cat:'Finanças',txt:'Consolida os teus cartões de crédito e paga sempre o saldo total no fim do mês. Os juros de crédito em Portugal rondam os 20% ao ano — o pior investimento possível.',sub:'Elimina os juros mais caros'},
  {cat:'Finanças',txt:'Cria um fundo de emergência equivalente a 3-6 meses de despesas antes de investir. Sem ele, qualquer imprevisto desfaz o teu progresso.',sub:'A base de tudo'},
  {cat:'Investimento',txt:'O ETF VWCE (Vanguard FTSE All-World) dá exposição a mais de 3.500 empresas de todo o mundo por um custo anual de apenas 0,22%. É o ponto de partida ideal.',sub:'Diversificação máxima, custo mínimo'},
  {cat:'Investimento',txt:'Investe regularmente (dollar-cost averaging) em vez de esperar pelo momento certo. Quem investe 200€/mês durante 20 anos bate quase sempre quem espera pelo timing perfeito.',sub:'Consistência > perfeição'},
  {cat:'Investimento',txt:'O DeGiro e o Trade Republic são as plataformas com menores comissões em Portugal. O Trade Republic oferece ainda 4% de juro sobre saldo em conta.',sub:'Menos comissões = mais retorno'},
  {cat:'Investimento',txt:'Em Portugal, os juros e mais-valias de investimentos são tributados a 28% (ou englobamento se vantajoso). Considera sempre o impacto fiscal antes de vender.',sub:'IRS sobre investimentos'},
  {cat:'Habitação',txt:'Renegocia a tua hipoteca a cada 2-3 anos. Com a subida das taxas Euribor, muitos bancos estão abertos a renegociar spreads para não perder clientes.',sub:'Potencial de poupança: centenas/mês'},
  {cat:'Habitação',txt:'O crédito ao consumo para obras tem juros altíssimos. Se precisas de renovar casa, pesquisa o Crédito Bonificado à Habitação do IHRU para jovens e famílias.',sub:'Taxas subsidiadas disponíveis'},
  {cat:'Habitação',txt:'Pede uma auditoria energética gratuita à tua câmara municipal. Muitos municípios oferecem este serviço e pode revelar poupanças significativas.',sub:'Serviço gratuito frequentemente'},
  {cat:'Saúde',txt:'Pede sempre a receita verde e compra genéricos na farmácia. Os medicamentos genéricos têm exatamente a mesma substância ativa — a lei obriga a isso.',sub:'Até 80% mais barato'},
  {cat:'Saúde',txt:'O ADSE, se tiveres acesso, pode ser complementado com um seguro de saúde privado de baixo custo para cobrir as lacunas. Compara em comparadores como Raize ou ComparaJá.',sub:'Saúde sem pagar em excesso'},
  {cat:'Saúde',txt:'As consultas nos Centros de Saúde são gratuitas ou têm taxa moderadora baixa. Para patologias não urgentes, evita urgências hospitalares — a taxa é muito superior.',sub:'Sistema público: usa-o com sabedoria'},
  {cat:'Lazer',txt:'O Cartão Jovem (<30 anos) dá descontos de 25-50% em museus, cinemas, transporte e alojamento em Portugal e na Europa. Se ainda és elegível, é obrigatório.',sub:'Descontos em toda a Europa'},
  {cat:'Lazer',txt:'Os museus nacionais em Portugal são gratuitos aos domingos de manhã. Inclui o Museu Nacional de Arte Antiga, o Museu do Azulejo e muitos outros.',sub:'Cultura gratuita ao domingo'},
  {cat:'Lazer',txt:'Partilha subscrições de streaming com família ou amigos. O plano familiar do Spotify custa 17,99€ para 6 pessoas — menos de 3€ por pessoa.',sub:'Partilha = poupança imediata'},
  {cat:'Lazer',txt:'Usa a Biblioteca Municipal. Para além de livros, muitas oferecem acesso gratuito a revistas digitais, filmes e cursos online através de plataformas como a Cantook.',sub:'Acesso a conteúdo gratuito'},
  {cat:'Tecnologia',txt:'Antes de renovar o telemóvel, verifica as ofertas de telemóveis recondicionados certificados. Um iPhone recondicionado pode custar 40% menos com garantia oficial.',sub:'Mesmo produto, menor preço'},
  {cat:'Tecnologia',txt:'Compara tarifas de telemóvel em comparadores como o ComparaJá.pt. Mudar de operador pode poupar 10-20€/mês sem perder qualidade de serviço.',sub:'Poupa até 240€/ano'},
  {cat:'Tecnologia',txt:'Cancela as subscrições que não usas. O português médio tem 4-5 subscrições ativas e usa regularmente apenas 2. Revê os débitos diretos este mês.',sub:'Subscrições esquecidas = dinheiro perdido'},
  {cat:'Alimentação',txt:'Cozinha em grandes quantidades ao fim de semana (meal prep). Além de poupar tempo, reduz o desperdício alimentar e evita a tentação de pedir comida ao domicílio.',sub:'Menos desperdício, mais poupança'},
  {cat:'Alimentação',txt:'A água da torneira em Portugal é segura para beber na maioria dos concelhos. Usar um filtro de carvão ativado elimina qualquer sabor residual por menos de 30€/ano.',sub:'Versus garrafas: poupa centenas/ano'},
  {cat:'Alimentação',txt:'Aproveita as promoções de congelados. Legumes congelados têm o mesmo valor nutricional que frescos e duram meses — sem desperdício.',sub:'Nutrição igual, desperdício zero'},
  {cat:'Finanças',txt:'Separa os teus objetivos financeiros em contas ou subcategorias diferentes. Quem tem objetivos com nomes concretos (Viagem, Emergência, Casa) poupa 2x mais.',sub:'Psicologia do dinheiro em ação'},
  {cat:'Finanças',txt:'Usa a regra 50/30/20: 50% necessidades, 30% desejos, 20% poupança e investimento. É simples, eficaz e adaptável à realidade portuguesa.',sub:'Framework de orçamento comprovada'},
  {cat:'Habitação',txt:'Negocia o arrendamento antes de renovar. Em zonas com alta oferta, pedir uma redução de 5-10% ou incluir despesas (internet, condomínio) é cada vez mais comum.',sub:'Negociar não custa nada'},
  {cat:'Investimento',txt:'Os certificados do Tesouro Aforro e Poupança do Estado Português são garantidos pelo Estado e têm rendimentos competitivos. São ideais para o fundo de emergência.',sub:'Garantia do Estado + rendimento'},
  {cat:'Finanças',txt:'Paga as multas e coimas o mais cedo possível. Em Portugal, podes ter descontos de até 50% se pagares nos primeiros dias. O adiamento tem custo real.',sub:'Desconto por pagamento antecipado'},
  {cat:'Supermercado',txt:'Os cartões de fidelidade do Continente, Pingo Doce e Auchan acumulam descontos reais. Ativa as promoções personalizadas na app antes de cada compra.',sub:'Cartões de fidelidade compensam'},
  {cat:'Finanças',txt:'Faz o exercício do "custo em horas de trabalho". Se ganhas 10€/hora líquidos, um jantar de 40€ custa-te 4 horas de trabalho. Muda a perspetiva sobre o consumo.',sub:'A unidade real do dinheiro'},
  {cat:'Energia',txt:'Instala tomadas inteligentes com timer para o esquentador, aquecedores e outros equipamentos de alto consumo. O investimento recupera-se em 2-3 meses.',sub:'Automação ao serviço da poupança'},
  {cat:'Transportes',txt:'Sempre que possível, combina viagens e recados. Cada saída de carro desnecessária consome combustível, tempo e desgaste. Planear poupa dinheiro.',sub:'A viagem mais cara é a que não se planeia'},
  {cat:'Investimento',txt:'Reinveste sempre os dividendos e juros. O efeito de juros compostos só funciona a 100% quando não retiras os rendimentos. Deixa o dinheiro trabalhar.',sub:'Juros compostos: a oitava maravilha'},
  {cat:'Finanças',txt:'Antes de qualquer compra acima de 50€, espera 48 horas. Este período de reflexão elimina a maioria das compras por impulso sem nenhum sacrifício real.',sub:'A regra das 48 horas'},
];

export function getDicaDoDia() {
  const hoje = new Date();
  const diaDoAno = Math.floor((hoje - new Date(hoje.getFullYear(), 0, 0)) / (1000 * 60 * 60 * 24));
  const idx = diaDoAno % DICAS.length;
  return { ...DICAS[idx], num: idx + 1 };
}
